### PR TITLE
translation in Bahasa (Indonesian)

### PR DESCRIPTION
**Pull request by faizzaidi**
Hi @PauloASilva, 

I am raising PR for Bahasa (Indonesian) translation. 
https://github.com/OWASP/API-Security/issues/66

Kindly, let me know if any changes are needed.

Thanks,
Faiz

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hey,
I would love to make the API Security Top 10 available in your language, but we need to find someone to help reviewing your translation here on GitHub.

Anyone you may know of that can help here?

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
In fact it seems that @tedher already did it :thinking: 

There's [this last comment](https://github.com/OWASP/API-Security/issues/66#issuecomment-1783848350) from @tedher: @faizzaidi do you plan to address it?

**Comment by faizzaidi** [comment]
Hi @PauloASilva ,

Yes, I have reviewed and merged the changes from @tedher.

**Comment by PauloASilva** [comment]
Alright, so it is ready for merge, right?

**Comment by faizzaidi** [comment]
yes

**Comment by PauloASilva** [comment]
Hi @faizzaidi,
There are some fixes required in order to properly build Bahasa translation.

Please review the links in the following files which in general point to a non-existing file whose name ends with `-id.md`:

* `editions/2019/ba/0x02-foreword.md`
* `editions/2019/ba/0x03-introduction.md`
* `editions/2019/ba/0x04-release-notes.md`
* `editions/2019/ba/0xd0-about-data.md`
* `editions/2023/ba/0x00-toc.md`
* `editions/2023/ba/0x02-foreword.md`
* `editions/2023/ba/0xa1-broken-object-level-authorization.md`

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
I also need your help to translate a few Mkdocs Material template keywords into Bahasa.

1. Create a new file `ba.html` at `docs/overrides/partials/languages`
2. Copy [this](https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/src/templates/partials/languages/en.html) into the new `ba.html` file you've created (there's an [Indonesian version](https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/src/templates/partials/languages/id.html) available)
3. Translate the values
4. Commit the changes

Thanks,
Paulo A. Silva

**Comment by faizzaidi** [comment]
Hi @PauloASilva ,

Sure, I will update it and let you know.

**Comment by PauloASilva** [comment]
Hi folks,
Please check [these changes][1], reviewing your translation to understand whether they apply. Nested lists should use 4 spaces indentation.

Cheers,
Paulo A. Silva
[1]: https://github.com/OWASP/API-Security/compare/v2.4.0...v2.4.1

**Comment by faizzaidi** [comment]
Hi @PauloASilva, 

I have added the changes and fixed the redirection issues.  
Please let me know if anything else needs to be done. 

Thanks,
Faiz

**Comment by PauloASilva** [comment]
Hi Folks,
Sorry about the delay to get this merged but additional changes were required.

Both translations (2019 and 2023) were released in [v2.5.0](https://github.com/OWASP/API-Security/releases/tag/v2.5.0) and are now live: [2019](https://owasp.org/API-Security/editions/2019/id/0x00-header/) and [2023](https://owasp.org/API-Security/editions/2023/id/0x00-header/).

Cheers,
Paulo A. Silva

**Comment by tedher** [comment]
Hi Paulo, I saw that the 0xa2 title in this link (
https://owasp.org/API-Security/editions/2023/id/0x00-header/) is different
with the rest:

[image: image.png]
How to fix this?

**Comment by PauloASilva** [comment]
Hi @tedher
Not sure what does "different with the rest" means: the image in your comment is missing.

Anyway, the way to go is Pull Request: would you like to open it?

Cheers,
Paulo A. Silva

**Comment by faizzaidi** [comment]
Hi @PauloASilva ,

I will check the issue and update this issue soon. 

Thanks,
Faiz

**Comment by faizzaidi** [comment]
Hi @PauloASilva,

Here is the pull request with the fix for this issue:

https://github.com/OWASP/API-Security/pull/135

Feel free to let me know if you need anything else.

Thanks,
Faiz

**Pull request merged**
