### PR TITLE
2019 - 0xa6-mass-assignment remove spurious period

### PR DESCRIPTION
**Pull request by kingthorin**
Remove trailing period within JSON example.

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hi @kingthorin,
Thanks for your interest.

I can you please do the same change for all available translations?

Cheers,
Paulo A. Silva

**Comment by kingthorin** [comment]
Sure I'll look through those and check.

**Comment by kingthorin** [comment]
@PauloASilva done

**Comment by kingthorin** [comment]
Ping @PauloASilva

**Comment by kingthorin** [comment]
@PauloASilva is something still needed here?

**Comment by PauloASilva** [comment]
Hi @kingthorin,
Nop, your PR looks OK. It should be just a matter of time to merge it.
Since I'll have to update all the ODTs and PDFs, and there are other open issues with minor changes, I'll try to do them all at once.

Thanks for your enthusiasm.

Cheers,
Paulo A. Silva

**Pull request merged**
