### PR TITLE
Translation/fa

### PR DESCRIPTION
**Pull request by This-is-Neo**
@PauloASilva Hello Dear Paulo! Persian Translation is done.

### CODE REVIEW

**Comment by PauloASilva** [comment]
@This-is-Neo I've done a quick check on changed files: the source files should be kept in Markdown format but all your files have a `.docx` extension. Can you please fix it?

**Comment by This-is-Neo** [comment]
@PauloASilva Yes of course.

**Comment by PauloASilva** [comment]
@This-is-Neo following the OWASP vendor-neutral approach, I'll have to kindly ask you to remove any reference to RNP such as the one found in the Acknowledgements sections. We will be glad to credit those responsible for the translation, linking their name/nickname to a social profile (e.g. Twitter, GitHub, Linkedin) as you can [see here](https://owasp.org/www-project-api-security/#div-translations).

Best,
Paulo A. Silva

**Comment by This-is-Neo** [comment]
@PauloASilva Hello Dear Paulo!
MD Files were added and  RNPG logo was removed.
I would be glad to credit the following:
Alireza Mostame: https://www.linkedin.com/in/alireza-mostame-29970b242
Mohammad Reza Ismaeli Taba: https://www.linkedin.com/in/rezataba
Amirmahdi Nowbakht: https://www.linkedin.com/in/amirmahdi-nowbakht-3b8865200
RNPG: https://www.linkedin.com/company/raspina-net-pars/

**Comment by This-is-Neo** [comment]
@PauloASilva 
@ErezYalon 
Dear Paulo and Erez! I would be glad if you could proceed with approving the pull request or inform us about possible changes that need to be applied on the work.
Thanks :)

**Comment by This-is-Neo** [comment]
Dear @PauloASilva We are happy to be a small part of this project and we're ready to be more engaged in upcoming versions and tasks, wherever and however you see fit.
Thanks :)

**Pull request closed without merging**
