### PR TITLE
translation russian

### PR DESCRIPTION
**Pull request by eugenebmx**
Translation: Eugene Rojavski (eugenebmx)
Proofreading: act1on3, keni0k

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hi @eugenebmx and team,
thanks for giving back.

Can you please provide Twitter handles, Linkedin pages, ... so that we can credit your work in [the translations list][1]?

Cheers,
Paulo A. Silva

[1]: https://owasp.org/www-project-api-security/#div-translations

**Comment by PauloASilva** [comment]
Although you have changed the PR title, based on source files status, I am assuming this is still a work in progress.

Please, feel free to get back to me if further assistance is required.

Cheers,
Paulo A. Silva

**Comment by eugenebmx** [comment]
🤦 forgot to push the latest changes. Updated development branch in my repo

**Comment by eugenebmx** [comment]
got too excited and forgot a couple of things. sorry to bother you before it's all ready.

**Comment by eugenebmx** [comment]
typo-free and odt\pdf updated

**Comment by eugenebmx** [comment]
Translation: Eugene Rojavski (twitter @EugeneRojavski)
Proofreading: act1on3 (twitter @act1on3), keni0k

**Comment by PauloASilva** [comment]
Hi @eugenebmx,
Thank you and your team for the translation.

It was already released ([v1.5.0](https://github.com/OWASP/API-Security/releases/tag/v1.5.0)) and a new entry was added to the [translations list](https://owasp.org/www-project-api-security/#div-translations).

Cheers,
Paulo A. Silva

**Pull request merged**
