### PR TITLE
Update 0xd1-acknowledgments.md

### PR DESCRIPTION
**Pull request by ModhakV**
okayy?

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hey @ModhakV,
Unfortunately it is not OK: this PR would replace the `en` (original) version

What are you trying to contribute: is it the Hindi Translation (#59)?
If that is the case, then you've missed step 3. from [my comment](https://github.com/OWASP/API-Security/issues/59#issuecomment-1385703065).

Please update your branch accordingly.
No partial translations will be merged.

Cheers,
Paulo A. Silva

**Comment by ModhakV** [comment]
Hey @PauloASilva 
My apologies. Am new to this, I just read your comment and now am gonna make it right.

**Comment by PauloASilva** [comment]
Hi @ModhakV,
No need to apologize.
Let me know in case you need some guidance.

Cheers,
Paulo A. Silva

**Comment by LaurentCB** [comment]
Are translators acknowledged as contributors in those files ? I think lot are missing.

**Comment by PauloASilva** [comment]
@LaurentCB 
> Are translators acknowledged as contributors in those files ? I think lot are missing.

Translators are acknowledged here: https://owasp.org/www-project-api-security/#div-translations
Translators are also free to add ["Translation Notes" like in the Portuguese translation][1]. Note that company logos or explicit references aren't allowed.

Does this answer your question?

Cheers,
Paulo A. Silva

[1]: https://github.com/OWASP/API-Security/blob/master/2019/pt-pt/src/0x04-release-notes.md#notas-da-tradu%C3%A7%C3%A3o

**Pull request closed without merging**
