### PR TITLE
Update the OWASP Secure Headers Project url.

### PR DESCRIPTION
**Pull request by righettod**
Hello,

First, thank you very much for this amazing project 🥇 

This PR update the link, referencing the OWASP Secure Headers Project, to the [right one](https://owasp.org/www-project-secure-headers/) in the different flavor of the file `0xa7-security-misconfiguration.md`:

image

Do not hesitate to contact me if we can push the integration a little further with the OSHP 😃 

Reference issue on the OSHP working plan: https://github.com/oshp/oshp-tracking/issues/3

Thank you very much in advance 😃

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hi @righettod,
Thanks for the PR.

Would you consider doing the same change in the corresponding ODT files and compile new PDFs?
Unfortunately this is a manual process. Since the redirect is working properly I would take a little longer to do it myself.

> Do not hesitate to contact me if we can push the integration a little further with the OSHP

What do you have in mind?
You can reach out to me by email at `paulo.silva[at]owasp.org`.

Best,
Paulo A. Silva

**Comment by righettod** [comment]
Hi @PauloASilva 

> Would you consider doing the same change in the corresponding ODT files and compile new PDFs? Unfortunately this is a manual process. Since the redirect is working properly I would take a little longer to do it myself.

For sure, I will update the PR ASAP with such content.

> What do you have in mind?

To be honest, nothing for the moment, but if during the evolution of the Top 10 API, there is a topics related to HTTP headers for which the OSHP can create and provide useful content then the OSHP team will do it for sure 😃  

Have a nice day

**Comment by righettod** [comment]
Hi @PauloASilva 

> Would you consider doing the same change in the corresponding ODT files and compile new PDFs? Unfortunately this is a manual process. Since the redirect is working properly I would take a little longer to do it myself.

Done in commit [228f592](https://github.com/OWASP/API-Security/pull/62/commits/228f592506b8c9803ec558c76857ba1fdfb79c03).

I used this version of **Libre Office** on a Windows 10 VM in US locale:

image

I used the following options for the PDF export (default ones - no option change):

image

Hope I did not break something 😃

**Comment by PauloASilva** [comment]
Hey @righettod,
I had to fix a missing reference to the project page in several translations and generate the `pt-br` PDF which had a single page, but we will need help with the `ar` and `fa` translations.

@Malajab, @KINGSABRI, @v-zafari, @ghookas, @This-is-Neo, can you help here, fixing the ODT and compiling the PDF?

Cheers,
Paulo A. Silva

**Comment by righettod** [comment]
Hi @PauloASilva 

I apologize, I tried my best to not break anything...

**Comment by PauloASilva** [comment]
> Hi @PauloASilva
> 
> I apologize, I tried my best to not break anything...

No worries.
Let's see if we get the required help from those responsible for the aforementioned translations.

**Comment by righettod** [comment]
thank you

**Comment by ghookas** [comment]
@PauloASilva 
How can i Help you?

**Comment by Malajab** [comment]
Thanks for ARABIC I will look at it.

**Comment by PauloASilva** [comment]
> @PauloASilva How can i Help you?

Can you please review the `FA` translation, ODT and PDF files, in this PR.
I believe they required some changes (e.g. page breaks).

Cheers,
Paulo A. Silva

**Comment by ghookas** [comment]
> > @PauloASilva How can i Help you?
> 
> Can you please review the `FA` translation, ODT and PDF files, in this PR. I believe they required some changes (e.g. page breaks).
> 
> Cheers, Paulo A. Silva

ok Sure

**Comment by PauloASilva** [comment]
@Malajab & @ghookas any progress here?

**Comment by Malajab** [comment]
Dear @PauloASilva 

I sent email with update version to you, kindly help us to update the files.
Thx

**Comment by PauloASilva** [comment]
> Dear @PauloASilva
> 
> I sent email with update version to you, kindly help us to update the files. Thx

Sure. Thanks for your help.

**Pull request closed without merging**
